Support modjy (i.e. Under Jython/Java/Tomcat)
CherryPy server works find under Jython but not under
modjy. find_handler() gets a Unicode string but translate expects
byte/str. Avoids:

    TypeError: character mapping must return integer, None or unicode